### ISSUE TITLE
error add dashboard

### ISSUE THREAD

**Issue by gejuking** [wyyr/crudbooster#1]
hello,

i love this skin 
but, i got error @getIndex not defined.  when set module as dashboard

**Comment by wyyr** [comment]
Hello, thank you. I will check it asap. Sorry for the late reply.

**Comment by wyyr** [comment]
> hello,
> 
> i love this skin but, i got error @getIndex not defined. when set module as dashboard

Hello, thank you. I will check it asap. Sorry for my late reply.

**Comment by gejuking** [comment]
ty for update

**Comment by wyyr** [comment]
No problem, let me know if you run into any more problems
